name: Terraform-Runner
description: Run Terraform stages using a custom container action.
inputs:
  ARM_SUBSCRIPTION_ID:
    description: Azure subscription id
    required: true
  ARM_TENANT_ID:
    description: Azure tenant id
    required: true
  ARM_CLIENT_ID:
    description: Azure client id
    required: true
  ARM_CLIENT_SECRET:
    description: Azure client secret
    required: true
  STATE_KEY:
    description: Unique backend state key prefix
    required: true
  TF_STAGE:
    description: Terraform stage directory to execute
    required: true
  DJANGO_SECRET_KEY_PROD:
    description: Django secret key value for stage 2 container deployment
    required: false
runs:
  using: docker
  image: Dockerfile
